### ISSUE TITLE
Question about Fortran support?

### ISSUE THREAD

**Issue by markyoder** [SETI/pds-julian#5]
Hi. I think this is a "somebody else's problem" question, but I thought I would ask.

I am trying to install FVCOM (https://github.com/FVCOM-GitHub/FVCOM), which has a  `julian` dependency, and I get an error that an include file, `fjulian.inc` cannot be found. Is that file part of the Julian package? Maybe a Fortran support module? Or -- recognizing that this part is way out of your domain but hoping for a guess anyway, would that more likely the Fortran/Julian interface on the FVCOM side?

Thank you in advance for help; guesses are welcome.

mark

**Comment by rfrenchseti** [comment]
Hi @markyoder,

Thanks for your query. The PDS Ring-Moon Systems Node supplies two unrelated Julian libraries. This one, `rms-julian`, is a purely Python implementation. The other one, which is a C implementation with FORTRAN support, is available near the bottom of this page under "Legacy C Libraries": https://pds-rings.seti.org/toolkits/

We have no affiliation with FVCOM, and in fact didn't even know they were using our C library until a few weeks ago. FVCOM apparently comes with a `libs` directory which includes archival copies of a variety of libraries it is dependent on, including our C julian library. The `README.txt` file in that directory doesn't seem to explain what to do with our library, and neither does the top-level `README.md` file, so I can't help you there.

If you have already "un-tar"ed the dependent libraries in the `libs` directory and your compile is still failing, perhaps you placed them in the wrong location. I'm afraid you'll have to contact the FVCOM maintainers for further support in that case.

**Comment by markyoder** [comment]
Hi @rfrencheseti - 
Wow, thanks for this. I really expected a (justly warranted), "Not my problem, good luck!" response. This looks great; I'll dig into it and see how it goes! Thanks for the info.

mark
